#==========================================================
#= Promo Articoli Web Service - Versione JWT
#==========================================================

server:
  port: 8091
  
logging:
  level:
    it.ghismo: DEBUG
    
spring:
  application:
    name: PromoWebService

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      
  datasource:
    initialization-mode: always
    password: banana
    platform: postgres
    url: jdbc:postgresql://192.168.1.9:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
  header: Authorization
  secret: Ghismo1979@DrizztDoUrden

services:
  gestuser:
    url: http://localhost:8019/api/utenti/cerca/userid/
    security-uid: UserRead
    security-pwd: read$

